## Travis CI Integration
language: csharp
solution: SimpleTest.Analyzer.sln
install:
 - sudo apt-get install nunit-console
 - nuget restore SimpleTest.Analyzer.sln
script:
 - xbuild /p:Configuration=Debug SimpleTest.Analyzer.sln
 - nunit-console ./SimpleTest.Analyzer.Tests/bin/Debug/SimpleTest.Analyzer.Tests.dll